#ifndef CHAT_PAGE_H
#define CHAT_PAGE_H

static const char* CHAT_PAGE_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>WII-AI Chatbot</title>\n"
"  <style>\n"
"    :root { color-scheme: light; }\n"
"    body { margin: 0; font-family: -apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif; background: linear-gradient(#f7fbff,#e4eef7); color: #1d3557; }\n"
"    .wrap { max-width: 900px; margin: 0 auto; min-height: 100vh; display: flex; flex-direction: column; }\n"
"    header { padding: 18px 16px 10px; text-align: center; }\n"
"    h1 { margin: 0; font-size: clamp(1.4rem,4vw,2rem); color: #0b5cab; }\n"
"    .status { font-size: .95rem; color: #3a6ea5; margin-top: 6px; }\n"
"    #chat { flex: 1; overflow-y: auto; padding: 14px; display: flex; flex-direction: column; gap: 10px; }\n"
"    .msg { max-width: 80%; padding: 12px 14px; border-radius: 16px; font-size: 1rem; line-height: 1.35; box-shadow: 0 1px 2px rgba(0,0,0,.08); }\n"
"    .user { align-self: flex-end; background: #1389ff; color: #fff; border-bottom-right-radius: 4px; }\n"
"    .ai { align-self: flex-start; background: #edf2f7; color: #1b2d42; border-bottom-left-radius: 4px; }\n"
"    form { display: flex; gap: 10px; padding: 12px; background: #ffffffcc; border-top: 1px solid #d6e3f2; position: sticky; bottom: 0; }\n"
"    input { flex: 1; font-size: 1rem; border: 1px solid #aac8e8; border-radius: 12px; padding: 12px; }\n"
"    button { font-size: 1rem; font-weight: 600; border: none; border-radius: 12px; padding: 12px 18px; background: #0b5cab; color: white; min-width: 82px; }\n"
"    button:active { transform: translateY(1px); }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"wrap\">\n"
"    <header>\n"
"      <h1>WII-AI Chatbot 🎮</h1>\n"
"      <div class=\"status\">Connected to Wii AI Server</div>\n"
"    </header>\n"
"    <main id=\"chat\" aria-live=\"polite\"></main>\n"
"    <form id=\"chatForm\">\n"
"      <input id=\"message\" placeholder=\"Ask the Wii anything...\" autocomplete=\"off\" />\n"
"      <button type=\"submit\">Send</button>\n"
"    </form>\n"
"  </div>\n"
"  <script>\n"
"    const chat = document.getElementById('chat');\n"
"    const form = document.getElementById('chatForm');\n"
"    const message = document.getElementById('message');\n"
"\n"
"    function addBubble(text, who) {\n"
"      const div = document.createElement('div');\n"
"      div.className = 'msg ' + who;\n"
"      div.textContent = text;\n"
"      chat.appendChild(div);\n"
"      chat.scrollTop = chat.scrollHeight;\n"
"    }\n"
"\n"
"    addBubble(\"Hello! I'm an AI running on a Nintendo Wii. Ask me anything!\", 'ai');\n"
"\n"
"    form.addEventListener('submit', async (e) => {\n"
"      e.preventDefault();\n"
"      const text = message.value.trim();\n"
"      if (!text) return;\n"
"      addBubble(text, 'user');\n"
"      message.value = '';\n"
"      try {\n"
"        const res = await fetch('/chat?msg=' + encodeURIComponent(text));\n"
"        if (!res.ok) throw new Error('HTTP ' + res.status);\n"
"        const data = await res.json();\n"
"        addBubble(data.response || 'No response from Wii AI.', 'ai');\n"
"      } catch (err) {\n"
"        addBubble('Connection error. Make sure your iPad is on the same WiFi as the Wii.', 'ai');\n"
"      }\n"
"    });\n"
"  </script>\n"
"</body>\n"
"</html>\n";

#endif
